//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subs.XMLServiceTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOTP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference1.SendOTPResponse SendOTP(Subs.XMLServiceTest.ServiceReference1.SendOTPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOTP", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.SendOTPResponse> SendOTPAsync(Subs.XMLServiceTest.ServiceReference1.SendOTPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse Authorize(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse> AuthorizeAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorizeMIC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference1.AuthorizeMICResponse AuthorizeMIC(Subs.XMLServiceTest.ServiceReference1.AuthorizeMICRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorizeMIC", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizeMICResponse> AuthorizeMICAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizeMICRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorizeToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference1.AuthorizeTokenResponse AuthorizeToken(Subs.XMLServiceTest.ServiceReference1.AuthorizeTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorizeToken", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizeTokenResponse> AuthorizeTokenAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizeTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorizations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse Authorizations(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorizations", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse> AuthorizationsAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEMailByCustomerId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse FindEMailByCustomerId(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEMailByCustomerId", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse> FindEMailByCustomerIdAsync(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse FindCustomerIdByEmail(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse> FindCustomerIdByEmailAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByNationalId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse FindCustomerIdByNationalId(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByNationalId", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse> FindCustomerIdByNationalIdAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string sourceField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int yearField;
        
        private int monthField;
        
        private int customerIdField;
        
        private int productIdField;
        
        private int seatsField;
        
        private System.DateTime expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TokenResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int seatsField;
        
        private string reasonField;
        
        private System.DateTime expirationDateField;
        
        private string titleField;
        
        private string firstNameField;
        
        private string surnameField;
        
        private string customerIdField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MICResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int seatsField;
        
        private string reasonField;
        
        private System.DateTime expirationDateField;
        
        private string titleField;
        
        private string firstNameField;
        
        private string surnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SeatResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int seatsField;
        
        private string reasonField;
        
        private System.DateTime expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOTP", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOTPRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pCustomerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pOTP;
        
        public SendOTPRequest() {
        }
        
        public SendOTPRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pCustomerId, int pOTP) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pCustomerId = pCustomerId;
            this.pOTP = pOTP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOTPResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOTPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendOTPResult;
        
        public SendOTPResponse() {
        }
        
        public SendOTPResponse(bool SendOTPResult) {
            this.SendOTPResult = SendOTPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authorize", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pProductId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pReceiverId;
        
        public AuthorizeRequest() {
        }
        
        public AuthorizeRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pProductId, int pReceiverId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pProductId = pProductId;
            this.pReceiverId = pReceiverId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.SeatResult AuthorizeResult;
        
        public AuthorizeResponse() {
        }
        
        public AuthorizeResponse(Subs.XMLServiceTest.ServiceReference1.SeatResult AuthorizeResult) {
            this.AuthorizeResult = AuthorizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeMIC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeMICRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pReceiverId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int pProductId;
        
        public AuthorizeMICRequest() {
        }
        
        public AuthorizeMICRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pReceiverId, string pPassword, int pProductId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pReceiverId = pReceiverId;
            this.pPassword = pPassword;
            this.pProductId = pProductId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeMICResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeMICResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.MICResult AuthorizeMICResult;
        
        public AuthorizeMICResponse() {
        }
        
        public AuthorizeMICResponse(Subs.XMLServiceTest.ServiceReference1.MICResult AuthorizeMICResult) {
            this.AuthorizeMICResult = AuthorizeMICResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeToken", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeTokenRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pTokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pProductId;
        
        public AuthorizeTokenRequest() {
        }
        
        public AuthorizeTokenRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pTokenId, int pProductId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pTokenId = pTokenId;
            this.pProductId = pProductId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeTokenResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.TokenResult AuthorizeTokenResult;
        
        public AuthorizeTokenResponse() {
        }
        
        public AuthorizeTokenResponse(Subs.XMLServiceTest.ServiceReference1.TokenResult AuthorizeTokenResult) {
            this.AuthorizeTokenResult = AuthorizeTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authorizations", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizationsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        public AuthorizationsRequest() {
        }
        
        public AuthorizationsRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader) {
            this.AuthorizationHeader = AuthorizationHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizationsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationResult[] AuthorizationsResult;
        
        public AuthorizationsResponse() {
        }
        
        public AuthorizationsResponse(Subs.XMLServiceTest.ServiceReference1.AuthorizationResult[] AuthorizationsResult) {
            this.AuthorizationsResult = AuthorizationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindEMailByCustomerId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindEMailByCustomerIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pCustomerId;
        
        public FindEMailByCustomerIdRequest() {
        }
        
        public FindEMailByCustomerIdRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pCustomerId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pCustomerId = pCustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindEMailByCustomerIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindEMailByCustomerIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindEMailByCustomerIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pEmailAddress;
        
        public FindEMailByCustomerIdResponse() {
        }
        
        public FindEMailByCustomerIdResponse(bool FindEMailByCustomerIdResult, string pEmailAddress) {
            this.FindEMailByCustomerIdResult = FindEMailByCustomerIdResult;
            this.pEmailAddress = pEmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByEmailRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EmailAddress;
        
        public FindCustomerIdByEmailRequest() {
        }
        
        public FindCustomerIdByEmailRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, string EmailAddress) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.EmailAddress = EmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindCustomerIdByEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CustomerId;
        
        public FindCustomerIdByEmailResponse() {
        }
        
        public FindCustomerIdByEmailResponse(bool FindCustomerIdByEmailResult, int CustomerId) {
            this.FindCustomerIdByEmailResult = FindCustomerIdByEmailResult;
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByNationalId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByNationalIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NationalId;
        
        public FindCustomerIdByNationalIdRequest() {
        }
        
        public FindCustomerIdByNationalIdRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, string NationalId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.NationalId = NationalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByNationalIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByNationalIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindCustomerIdByNationalIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CustomerId;
        
        public FindCustomerIdByNationalIdResponse() {
        }
        
        public FindCustomerIdByNationalIdResponse(bool FindCustomerIdByNationalIdResult, int CustomerId) {
            this.FindCustomerIdByNationalIdResult = FindCustomerIdByNationalIdResult;
            this.CustomerId = CustomerId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Subs.XMLServiceTest.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Subs.XMLServiceTest.ServiceReference1.ServiceSoap>, Subs.XMLServiceTest.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Subs.XMLServiceTest.ServiceReference1.SendOTPResponse SendOTP(Subs.XMLServiceTest.ServiceReference1.SendOTPRequest request) {
            return base.Channel.SendOTP(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.SendOTPResponse> SendOTPAsync(Subs.XMLServiceTest.ServiceReference1.SendOTPRequest request) {
            return base.Channel.SendOTPAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse Authorize(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request) {
            return base.Channel.Authorize(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse> AuthorizeAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request) {
            return base.Channel.AuthorizeAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.AuthorizeMICResponse AuthorizeMIC(Subs.XMLServiceTest.ServiceReference1.AuthorizeMICRequest request) {
            return base.Channel.AuthorizeMIC(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizeMICResponse> AuthorizeMICAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizeMICRequest request) {
            return base.Channel.AuthorizeMICAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.AuthorizeTokenResponse AuthorizeToken(Subs.XMLServiceTest.ServiceReference1.AuthorizeTokenRequest request) {
            return base.Channel.AuthorizeToken(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizeTokenResponse> AuthorizeTokenAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizeTokenRequest request) {
            return base.Channel.AuthorizeTokenAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse Authorizations(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request) {
            return base.Channel.Authorizations(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse> AuthorizationsAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request) {
            return base.Channel.AuthorizationsAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse FindEMailByCustomerId(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request) {
            return base.Channel.FindEMailByCustomerId(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse> FindEMailByCustomerIdAsync(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request) {
            return base.Channel.FindEMailByCustomerIdAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse FindCustomerIdByEmail(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request) {
            return base.Channel.FindCustomerIdByEmail(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse> FindCustomerIdByEmailAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request) {
            return base.Channel.FindCustomerIdByEmailAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse FindCustomerIdByNationalId(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request) {
            return base.Channel.FindCustomerIdByNationalId(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse> FindCustomerIdByNationalIdAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request) {
            return base.Channel.FindCustomerIdByNationalIdAsync(request);
        }
    }
}
