//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subs.XMLServiceTest.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since message AuthorizeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference2.AuthorizeResponse Authorize(Subs.XMLServiceTest.ServiceReference2.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.AuthorizeResponse> AuthorizeAsync(Subs.XMLServiceTest.ServiceReference2.AuthorizeRequest request);
        
        // CODEGEN: Generating message contract since message AuthorizationsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorizations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference2.AuthorizationsResponse Authorizations(Subs.XMLServiceTest.ServiceReference2.AuthorizationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorizations", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.AuthorizationsResponse> AuthorizationsAsync(Subs.XMLServiceTest.ServiceReference2.AuthorizationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEMailByCustomerId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdResponse FindEMailByCustomerId(Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEMailByCustomerId", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdResponse> FindEMailByCustomerIdAsync(Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailResponse FindCustomerIdByEmail(Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailResponse> FindCustomerIdByEmailAsync(Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByNationalId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdResponse FindCustomerIdByNationalId(Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByNationalId", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdResponse> FindCustomerIdByNationalIdAsync(Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressResponse InsertDeliveryAddress(Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressResponse> InsertDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressResponse GetDeliveryAddress(Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressResponse> GetDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressResponse UpdateDeliveryAddress(Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressResponse> UpdateDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string sourceField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeliveryAddressData2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int deliveryAddressIdField;
        
        private string phoneNumberField;
        
        private int countryIdField;
        
        private string provinceField;
        
        private string cityField;
        
        private string suburbField;
        
        private string streetField;
        
        private string streetExtensionField;
        
        private string streetSuffixField;
        
        private int streetIdField;
        
        private string streetNoField;
        
        private string buildingField;
        
        private string floorField;
        
        private string roomField;
        
        private string postCodeField;
        
        private string sDIField;
        
        private string modifiedByField;
        
        private System.DateTime modifiedOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DeliveryAddressId {
            get {
                return this.deliveryAddressIdField;
            }
            set {
                this.deliveryAddressIdField = value;
                this.RaisePropertyChanged("DeliveryAddressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
                this.RaisePropertyChanged("CountryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("Province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Suburb {
            get {
                return this.suburbField;
            }
            set {
                this.suburbField = value;
                this.RaisePropertyChanged("Suburb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string StreetExtension {
            get {
                return this.streetExtensionField;
            }
            set {
                this.streetExtensionField = value;
                this.RaisePropertyChanged("StreetExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string StreetSuffix {
            get {
                return this.streetSuffixField;
            }
            set {
                this.streetSuffixField = value;
                this.RaisePropertyChanged("StreetSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int StreetId {
            get {
                return this.streetIdField;
            }
            set {
                this.streetIdField = value;
                this.RaisePropertyChanged("StreetId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StreetNo {
            get {
                return this.streetNoField;
            }
            set {
                this.streetNoField = value;
                this.RaisePropertyChanged("StreetNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
                this.RaisePropertyChanged("Building");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
                this.RaisePropertyChanged("Floor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
                this.RaisePropertyChanged("Room");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SDI {
            get {
                return this.sDIField;
            }
            set {
                this.sDIField = value;
                this.RaisePropertyChanged("SDI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int yearField;
        
        private int monthField;
        
        private int customerIdField;
        
        private int productIdField;
        
        private int seatsField;
        
        private System.DateTime expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SeatResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int seatsField;
        
        private string reasonField;
        
        private System.DateTime expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authorize", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pProductId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pReceiverId;
        
        public AuthorizeRequest() {
        }
        
        public AuthorizeRequest(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, int pProductId, int pReceiverId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pProductId = pProductId;
            this.pReceiverId = pReceiverId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference2.SeatResult AuthorizeResult;
        
        public AuthorizeResponse() {
        }
        
        public AuthorizeResponse(Subs.XMLServiceTest.ServiceReference2.SeatResult AuthorizeResult) {
            this.AuthorizeResult = AuthorizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authorizations", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizationsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader;
        
        public AuthorizationsRequest() {
        }
        
        public AuthorizationsRequest(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader) {
            this.AuthorizationHeader = AuthorizationHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizationsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference2.AuthorizationResult[] AuthorizationsResult;
        
        public AuthorizationsResponse() {
        }
        
        public AuthorizationsResponse(Subs.XMLServiceTest.ServiceReference2.AuthorizationResult[] AuthorizationsResult) {
            this.AuthorizationsResult = AuthorizationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindEMailByCustomerId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindEMailByCustomerIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pCustomerId;
        
        public FindEMailByCustomerIdRequest() {
        }
        
        public FindEMailByCustomerIdRequest(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, int pCustomerId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pCustomerId = pCustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindEMailByCustomerIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindEMailByCustomerIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindEMailByCustomerIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pEmailAddress;
        
        public FindEMailByCustomerIdResponse() {
        }
        
        public FindEMailByCustomerIdResponse(bool FindEMailByCustomerIdResult, string pEmailAddress) {
            this.FindEMailByCustomerIdResult = FindEMailByCustomerIdResult;
            this.pEmailAddress = pEmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByEmailRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EmailAddress;
        
        public FindCustomerIdByEmailRequest() {
        }
        
        public FindCustomerIdByEmailRequest(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, string EmailAddress) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.EmailAddress = EmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindCustomerIdByEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CustomerId;
        
        public FindCustomerIdByEmailResponse() {
        }
        
        public FindCustomerIdByEmailResponse(bool FindCustomerIdByEmailResult, int CustomerId) {
            this.FindCustomerIdByEmailResult = FindCustomerIdByEmailResult;
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByNationalId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByNationalIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NationalId;
        
        public FindCustomerIdByNationalIdRequest() {
        }
        
        public FindCustomerIdByNationalIdRequest(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, string NationalId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.NationalId = NationalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByNationalIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByNationalIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindCustomerIdByNationalIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CustomerId;
        
        public FindCustomerIdByNationalIdResponse() {
        }
        
        public FindCustomerIdByNationalIdResponse(bool FindCustomerIdByNationalIdResult, int CustomerId) {
            this.FindCustomerIdByNationalIdResult = FindCustomerIdByNationalIdResult;
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDeliveryAddress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertDeliveryAddressRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pCustomerId;
        
        public InsertDeliveryAddressRequest() {
        }
        
        public InsertDeliveryAddressRequest(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData, int pCustomerId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pDeliveryAddressData = pDeliveryAddressData;
            this.pCustomerId = pCustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDeliveryAddressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertDeliveryAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InsertDeliveryAddressResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData;
        
        public InsertDeliveryAddressResponse() {
        }
        
        public InsertDeliveryAddressResponse(string InsertDeliveryAddressResult, Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData) {
            this.InsertDeliveryAddressResult = InsertDeliveryAddressResult;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryAddress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryAddressRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pDeliveryAddressId;
        
        public GetDeliveryAddressRequest() {
        }
        
        public GetDeliveryAddressRequest(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, int pDeliveryAddressId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pDeliveryAddressId = pDeliveryAddressId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryAddressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDeliveryAddressResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData;
        
        public GetDeliveryAddressResponse() {
        }
        
        public GetDeliveryAddressResponse(string GetDeliveryAddressResult, Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData) {
            this.GetDeliveryAddressResult = GetDeliveryAddressResult;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDeliveryAddress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateDeliveryAddressRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData;
        
        public UpdateDeliveryAddressRequest() {
        }
        
        public UpdateDeliveryAddressRequest(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDeliveryAddressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateDeliveryAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateDeliveryAddressResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData;
        
        public UpdateDeliveryAddressResponse() {
        }
        
        public UpdateDeliveryAddressResponse(string UpdateDeliveryAddressResult, Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData) {
            this.UpdateDeliveryAddressResult = UpdateDeliveryAddressResult;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Subs.XMLServiceTest.ServiceReference2.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Subs.XMLServiceTest.ServiceReference2.ServiceSoap>, Subs.XMLServiceTest.ServiceReference2.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Subs.XMLServiceTest.ServiceReference2.AuthorizeResponse Subs.XMLServiceTest.ServiceReference2.ServiceSoap.Authorize(Subs.XMLServiceTest.ServiceReference2.AuthorizeRequest request) {
            return base.Channel.Authorize(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference2.SeatResult Authorize(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, int pProductId, int pReceiverId) {
            Subs.XMLServiceTest.ServiceReference2.AuthorizeRequest inValue = new Subs.XMLServiceTest.ServiceReference2.AuthorizeRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.pProductId = pProductId;
            inValue.pReceiverId = pReceiverId;
            Subs.XMLServiceTest.ServiceReference2.AuthorizeResponse retVal = ((Subs.XMLServiceTest.ServiceReference2.ServiceSoap)(this)).Authorize(inValue);
            return retVal.AuthorizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.AuthorizeResponse> Subs.XMLServiceTest.ServiceReference2.ServiceSoap.AuthorizeAsync(Subs.XMLServiceTest.ServiceReference2.AuthorizeRequest request) {
            return base.Channel.AuthorizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.AuthorizeResponse> AuthorizeAsync(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, int pProductId, int pReceiverId) {
            Subs.XMLServiceTest.ServiceReference2.AuthorizeRequest inValue = new Subs.XMLServiceTest.ServiceReference2.AuthorizeRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.pProductId = pProductId;
            inValue.pReceiverId = pReceiverId;
            return ((Subs.XMLServiceTest.ServiceReference2.ServiceSoap)(this)).AuthorizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Subs.XMLServiceTest.ServiceReference2.AuthorizationsResponse Subs.XMLServiceTest.ServiceReference2.ServiceSoap.Authorizations(Subs.XMLServiceTest.ServiceReference2.AuthorizationsRequest request) {
            return base.Channel.Authorizations(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference2.AuthorizationResult[] Authorizations(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader) {
            Subs.XMLServiceTest.ServiceReference2.AuthorizationsRequest inValue = new Subs.XMLServiceTest.ServiceReference2.AuthorizationsRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            Subs.XMLServiceTest.ServiceReference2.AuthorizationsResponse retVal = ((Subs.XMLServiceTest.ServiceReference2.ServiceSoap)(this)).Authorizations(inValue);
            return retVal.AuthorizationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.AuthorizationsResponse> Subs.XMLServiceTest.ServiceReference2.ServiceSoap.AuthorizationsAsync(Subs.XMLServiceTest.ServiceReference2.AuthorizationsRequest request) {
            return base.Channel.AuthorizationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.AuthorizationsResponse> AuthorizationsAsync(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader) {
            Subs.XMLServiceTest.ServiceReference2.AuthorizationsRequest inValue = new Subs.XMLServiceTest.ServiceReference2.AuthorizationsRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            return ((Subs.XMLServiceTest.ServiceReference2.ServiceSoap)(this)).AuthorizationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdResponse Subs.XMLServiceTest.ServiceReference2.ServiceSoap.FindEMailByCustomerId(Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdRequest request) {
            return base.Channel.FindEMailByCustomerId(request);
        }
        
        public bool FindEMailByCustomerId(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, int pCustomerId, out string pEmailAddress) {
            Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdRequest inValue = new Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.pCustomerId = pCustomerId;
            Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdResponse retVal = ((Subs.XMLServiceTest.ServiceReference2.ServiceSoap)(this)).FindEMailByCustomerId(inValue);
            pEmailAddress = retVal.pEmailAddress;
            return retVal.FindEMailByCustomerIdResult;
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdResponse> FindEMailByCustomerIdAsync(Subs.XMLServiceTest.ServiceReference2.FindEMailByCustomerIdRequest request) {
            return base.Channel.FindEMailByCustomerIdAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailResponse Subs.XMLServiceTest.ServiceReference2.ServiceSoap.FindCustomerIdByEmail(Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailRequest request) {
            return base.Channel.FindCustomerIdByEmail(request);
        }
        
        public bool FindCustomerIdByEmail(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, string EmailAddress, out int CustomerId) {
            Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailRequest inValue = new Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.EmailAddress = EmailAddress;
            Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailResponse retVal = ((Subs.XMLServiceTest.ServiceReference2.ServiceSoap)(this)).FindCustomerIdByEmail(inValue);
            CustomerId = retVal.CustomerId;
            return retVal.FindCustomerIdByEmailResult;
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailResponse> FindCustomerIdByEmailAsync(Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByEmailRequest request) {
            return base.Channel.FindCustomerIdByEmailAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdResponse Subs.XMLServiceTest.ServiceReference2.ServiceSoap.FindCustomerIdByNationalId(Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdRequest request) {
            return base.Channel.FindCustomerIdByNationalId(request);
        }
        
        public bool FindCustomerIdByNationalId(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, string NationalId, out int CustomerId) {
            Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdRequest inValue = new Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.NationalId = NationalId;
            Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdResponse retVal = ((Subs.XMLServiceTest.ServiceReference2.ServiceSoap)(this)).FindCustomerIdByNationalId(inValue);
            CustomerId = retVal.CustomerId;
            return retVal.FindCustomerIdByNationalIdResult;
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdResponse> FindCustomerIdByNationalIdAsync(Subs.XMLServiceTest.ServiceReference2.FindCustomerIdByNationalIdRequest request) {
            return base.Channel.FindCustomerIdByNationalIdAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressResponse Subs.XMLServiceTest.ServiceReference2.ServiceSoap.InsertDeliveryAddress(Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressRequest request) {
            return base.Channel.InsertDeliveryAddress(request);
        }
        
        public string InsertDeliveryAddress(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, ref Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData, int pCustomerId) {
            Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressRequest inValue = new Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.pDeliveryAddressData = pDeliveryAddressData;
            inValue.pCustomerId = pCustomerId;
            Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressResponse retVal = ((Subs.XMLServiceTest.ServiceReference2.ServiceSoap)(this)).InsertDeliveryAddress(inValue);
            pDeliveryAddressData = retVal.pDeliveryAddressData;
            return retVal.InsertDeliveryAddressResult;
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressResponse> InsertDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference2.InsertDeliveryAddressRequest request) {
            return base.Channel.InsertDeliveryAddressAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressResponse Subs.XMLServiceTest.ServiceReference2.ServiceSoap.GetDeliveryAddress(Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressRequest request) {
            return base.Channel.GetDeliveryAddress(request);
        }
        
        public string GetDeliveryAddress(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, int pDeliveryAddressId, out Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData) {
            Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressRequest inValue = new Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.pDeliveryAddressId = pDeliveryAddressId;
            Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressResponse retVal = ((Subs.XMLServiceTest.ServiceReference2.ServiceSoap)(this)).GetDeliveryAddress(inValue);
            pDeliveryAddressData = retVal.pDeliveryAddressData;
            return retVal.GetDeliveryAddressResult;
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressResponse> GetDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference2.GetDeliveryAddressRequest request) {
            return base.Channel.GetDeliveryAddressAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressResponse Subs.XMLServiceTest.ServiceReference2.ServiceSoap.UpdateDeliveryAddress(Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressRequest request) {
            return base.Channel.UpdateDeliveryAddress(request);
        }
        
        public string UpdateDeliveryAddress(Subs.XMLServiceTest.ServiceReference2.AuthorizationHeader AuthorizationHeader, ref Subs.XMLServiceTest.ServiceReference2.DeliveryAddressData2 pDeliveryAddressData) {
            Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressRequest inValue = new Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.pDeliveryAddressData = pDeliveryAddressData;
            Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressResponse retVal = ((Subs.XMLServiceTest.ServiceReference2.ServiceSoap)(this)).UpdateDeliveryAddress(inValue);
            pDeliveryAddressData = retVal.pDeliveryAddressData;
            return retVal.UpdateDeliveryAddressResult;
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressResponse> UpdateDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference2.UpdateDeliveryAddressRequest request) {
            return base.Channel.UpdateDeliveryAddressAsync(request);
        }
    }
}
