//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPD.Business.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jobs", Namespace="http://schemas.datacontract.org/2004/07/MIMS.WcfService")]
    public enum Jobs : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIMSStatement = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://schemas.datacontract.org/2004/07/MIMS.WcfService")]
    [System.SerializableAttribute()]
    public partial class CustomerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CouncilNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CouncilNumber {
            get {
                return this.CouncilNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CouncilNumberField, value) != true)) {
                    this.CouncilNumberField = value;
                    this.RaisePropertyChanged("CouncilNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Due {
            get {
                return this.DueField;
            }
            set {
                if ((this.DueField.Equals(value) != true)) {
                    this.DueField = value;
                    this.RaisePropertyChanged("Due");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exists {
            get {
                return this.ExistsField;
            }
            set {
                if ((this.ExistsField.Equals(value) != true)) {
                    this.ExistsField = value;
                    this.RaisePropertyChanged("Exists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IActivator")]
    public interface IActivator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivator/Start", ReplyAction="http://tempuri.org/IActivator/StartResponse")]
        CPD.Business.ServiceReference1.StartResponse Start(CPD.Business.ServiceReference1.StartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivator/AuthoriseCPDIssue", ReplyAction="http://tempuri.org/IActivator/AuthoriseCPDIssueResponse")]
        CPD.Business.ServiceReference1.AuthoriseCPDIssueResponse AuthoriseCPDIssue(CPD.Business.ServiceReference1.AuthoriseCPDIssueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivator/GetCustomerInfo", ReplyAction="http://tempuri.org/IActivator/GetCustomerInfoResponse")]
        CPD.Business.ServiceReference1.GetCustomerInfoResponse GetCustomerInfo(CPD.Business.ServiceReference1.GetCustomerInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Start", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CPD.Business.ServiceReference1.Jobs pJob;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pDirectoryPath;
        
        public StartRequest() {
        }
        
        public StartRequest(CPD.Business.ServiceReference1.Jobs pJob, string pDirectoryPath) {
            this.pJob = pJob;
            this.pDirectoryPath = pDirectoryPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartResponse {
        
        public StartResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthoriseCPDIssue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthoriseCPDIssueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CustomerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IssueId;
        
        public AuthoriseCPDIssueRequest() {
        }
        
        public AuthoriseCPDIssueRequest(int CustomerId, int IssueId) {
            this.CustomerId = CustomerId;
            this.IssueId = IssueId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthoriseCPDIssueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthoriseCPDIssueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AuthoriseCPDIssueResult;
        
        public AuthoriseCPDIssueResponse() {
        }
        
        public AuthoriseCPDIssueResponse(bool AuthoriseCPDIssueResult) {
            this.AuthoriseCPDIssueResult = AuthoriseCPDIssueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CustomerId;
        
        public GetCustomerInfoRequest() {
        }
        
        public GetCustomerInfoRequest(int CustomerId) {
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CPD.Business.ServiceReference1.CustomerInfo GetCustomerInfoResult;
        
        public GetCustomerInfoResponse() {
        }
        
        public GetCustomerInfoResponse(CPD.Business.ServiceReference1.CustomerInfo GetCustomerInfoResult) {
            this.GetCustomerInfoResult = GetCustomerInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActivatorChannel : CPD.Business.ServiceReference1.IActivator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActivatorClient : System.ServiceModel.ClientBase<CPD.Business.ServiceReference1.IActivator>, CPD.Business.ServiceReference1.IActivator {
        
        public ActivatorClient() {
        }
        
        public ActivatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActivatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CPD.Business.ServiceReference1.StartResponse Start(CPD.Business.ServiceReference1.StartRequest request) {
            return base.Channel.Start(request);
        }
        
        public CPD.Business.ServiceReference1.AuthoriseCPDIssueResponse AuthoriseCPDIssue(CPD.Business.ServiceReference1.AuthoriseCPDIssueRequest request) {
            return base.Channel.AuthoriseCPDIssue(request);
        }
        
        public CPD.Business.ServiceReference1.GetCustomerInfoResponse GetCustomerInfo(CPD.Business.ServiceReference1.GetCustomerInfoRequest request) {
            return base.Channel.GetCustomerInfo(request);
        }
    }
}
